baseurl = "https://ways-choir-dev.gitlab.io"
# baseurl = "http://www.ways-choir.eu/"
title = "WAYS - WithAllYourSenses"
theme = "twenty"
languageCode = "de-de"

[languages]
[languages.de]
weight = 1
languageName = "Deutsch"

[languages.en]
weight = 2
languageName = "English"


[[languages.de.menu.main]]
    url = "/contact"
    name = "Kontakt"
    weight = 1000
    identifier = "menu_contact"

[[languages.de.menu.main]]
    name   = "Über uns"
    weight = 300
    identifier = "menu_about"

[[languages.de.menu.main]]
    url    = "/about/the-choir/"
    name   = "Der Chor"
    weight = 100
    parent = "menu_about"
    identifier = "menu_about_the_choir"


[[languages.en.menu.main]]
    url = "/contact"
    name = "Contact"
    weight = 1000
    identifier = "menu_contact"

[[languages.en.menu.main]]
    name   = "About us"
    weight = 300
    identifier = "menu_about"

[[languages.en.menu.main]]
    url    = "/about/the-choir/"
    name   = "the choir"
    weight = 100
    parent = "menu_about"
    identifier = "menu_about_the_choir"

[params]
[params.imagesConfig]
    cloudinaryURL = "https://res.cloudinary.com/ways-choir/image/upload"
    lightboxImageDownloadSize = "w_2000"


