baseurl = "https://www.ways-choir.eu/"
defaultContentLanguage = "de"
languageCode = "de-de"
theme = "twenty"
title = "WAYS - With All Your Senses"
[languages.de]
languageName = "Deutsch"
weight = 1
[[languages.de.menu.main]]
identifier = "menu_contact"
name = "Kontakt"
url = "/contact"
weight = 1000
[[languages.de.menu.main]]
identifier = "menu_about"
name = "Über uns"
weight = 300
[[languages.de.menu.main]]
identifier = "menu_about_the_choir"
name = "Der Chor"
parent = "menu_about"
url = "/the_choir/"
weight = 10
[[languages.de.menu.main]]
identifier = "menu_about_choirleader"
name = "Chorleitung"
parent = "menu_about"
url = "/choirleader/"
weight = 20
[[languages.de.menu.main]]
identifier = "menu_about_concerts"
name = "Konzerte"
parent = "menu_about"
url = "/events/"
weight = 50
[[languages.de.menu.main]]
identifier = "menu_about_photos"
name = "Fotos"
parent = "menu_about"
url = "/photos/"
weight = 90
[[languages.de.menu.main]]
identifier = "menu_about_videos"
name = "Videos"
parent = "menu_about"
url = "/videos/"
weight = 100
[[languages.de.menu.main]]
identifier = "menu_about_concert_archive"
name = "Konzert-Archiv"
parent = "menu_about"
url = "/events/archive/"
weight = 150
[[languages.de.menu.main]]
identifier = "menu_about_concert_archive"
name = "Concert Archive"
parent = "menu_about"
url = "/events/archive/"
weight = 150
[languages.en]
languageName = "English"
weight = 2
[[languages.en.menu.main]]
identifier = "menu_contact"
name = "Contact"
url = "/contact"
weight = 1000
[[languages.en.menu.main]]
identifier = "menu_about"
name = "About us"
weight = 300
[[languages.en.menu.main]]
identifier = "menu_about_the_choir"
name = "the choir"
parent = "menu_about"
url = "/the_choir/"
weight = 10
[[languages.en.menu.main]]
identifier = "menu_about_choirleader"
name = "the choir leader"
parent = "menu_about"
url = "/choirleader/"
weight = 20
[[languages.en.menu.main]]
identifier = "menu_about_concerts"
name = "Concerts"
parent = "menu_about"
url = "/events/"
weight = 50
[[languages.en.menu.main]]
identifier = "menu_about_photos"
name = "Photos"
parent = "menu_about"
url = "/photos/"
weight = 90
[[languages.en.menu.main]]
identifier = "menu_about_videos"
name = "Videos"
parent = "menu_about"
url = "/videos/"
weight = 100
[params]
date_format = "2. January, 2006"
email = "info@ways-choir.eu"
facebook = "https://www.facebook.com/WaysGospelSoulPopChoir"
instagram = "https://www.instagram.com/waysgospelsoulpopchoir/"
logo = "/v1577487364/logo_bg_white.png"
mapZoomFactor = "15"
time_format = "15:04"
twitter = "https://twitter.com/WAYS_choir"
[params.SEO.de]
description = "WAYS - With All Your Senses - Gospel-Soul-Pop-Chor aus Berlin unter der Leitung von Gunars Kalnins"
keywords = "WAYS, gospel, soul, pop, chor, berlin, gunars, kalnins"
[params.SEO.en]
description = "WAYS - With All Your Senses - Gospel-Soul-Pop-Choir from Berlin led by Gunars Kalnins"
keywords = "WAYS, gospel, soul, pop, choir, berlin, gunars, kalnins"
[params.contact]
address = "        <br>Bus-Stop e.V.\n        <br>Celsiusstr. 71-73\n        <br>12207 Berlin (Lichterfelde)\n        "
email = "info@ways-choir.eu"
name = "WAYS - With All Your Senses"
phone = "+49 176-31331855 (Renata)"
[params.contact.rehersal]
end = "22:00"
start = "19:00"
weekday = "Monday"
[params.imagesConfig]
cloudinaryURL = "https://res.cloudinary.com/ways-choir/image/upload"
lightboxImageDownloadSize = "w_2000"
listImageDefaultFile = "/images/ways-plakat-default.png"
listImageDownloadSize = "w_240"
logoImageDownloadSize = "w_1000"
thumbDownloadSize = "w_300,h_200,c_fill"
[params.latitude]
box_max = "52.4161"
box_min = "52.4071"
marker = "52.411600"
[params.longitude]
box_max = "13.3345"
box_min = "13.2945"
marker = "13.314500"
