# baseurl = "https://ways-choir-dev.gitlab.io/"
baseurl = "https://www.ways-choir.eu/"
defaultContentLanguage = "de"
languageCode = "de-de"
theme = "twenty"
title = "WAYS - WithAllYourSenses"
[languages.de]
languageName = "Deutsch"
weight = 1
[[languages.de.menu.main]]
identifier = "menu_contact"
name = "Kontakt"
url = "/contact"
weight = 1000
[[languages.de.menu.main]]
identifier = "menu_about"
name = "Über uns"
weight = 300
[[languages.de.menu.main]]
identifier = "menu_about_the_choir"
name = "Der Chor"
parent = "menu_about"
url = "/the_choir/"
weight = 10
[[languages.de.menu.main]]
identifier = "menu_about_choirleader"
name = "Chorleitung"
parent = "menu_about"
url = "/choirleader/"
weight = 20
[[languages.de.menu.main]]
identifier = "menu_about_concerts"
name = "Konzerte"
parent = "menu_about"
url = "/events/"
weight = 50
[[languages.de.menu.main]]
identifier = "menu_about_photos"
name = "Fotos"
parent = "menu_about"
url = "/photos/"
weight = 90
[[languages.de.menu.main]]
identifier = "menu_about_videos"
name = "Videos"
parent = "menu_about"
url = "/videos/"
weight = 100
[[languages.de.menu.main]]
identifier = "menu_about_concert_archive"
name = "Konzert-Archiv"
parent = "menu_about"
url = "/events/archive/"
weight = 150
[[languages.de.menu.main]]
identifier = "menu_about_concert_archive"
name = "Concert Archive"
parent = "menu_about"
url = "/events/archive/"
weight = 150
[languages.en]
languageName = "English"
weight = 2
[[languages.en.menu.main]]
identifier = "menu_contact"
name = "Contact"
url = "/contact"
weight = 1000
[[languages.en.menu.main]]
identifier = "menu_about"
name = "About us"
weight = 300
[[languages.en.menu.main]]
identifier = "menu_about_the_choir"
name = "the choir"
parent = "menu_about"
url = "/the_choir/"
weight = 10
[[languages.en.menu.main]]
identifier = "menu_about_choirleader"
name = "the choir leader"
parent = "menu_about"
url = "/choirleader/"
weight = 20
[[languages.en.menu.main]]
identifier = "menu_about_concerts"
name = "Concerts"
parent = "menu_about"
url = "/events/"
weight = 50
[[languages.en.menu.main]]
identifier = "menu_about_photos"
name = "Photos"
parent = "menu_about"
url = "/photos/"
weight = 90
[[languages.en.menu.main]]
identifier = "menu_about_videos"
name = "Videos"
parent = "menu_about"
url = "/videos/"
weight = 100
[params]
date_format = "2. January, 2006"
email = "info@ways-choir.eu"
facebook = "https://www.facebook.com/WaysChoirBerlin/"
instagram = "https://www.instagram.com/waysgospelsoulpopchoir/"
latitude = "52.4984045"
logo = "/v1577487364/logo_bg_white.png"
longitude = "13.297099600000024"
time_format = "15:04"
twitter = "https://twitter.com/WAYS_choir"
[params.contact]
address = "        <br>Pro Seniore Residenz Kurfürstendamm\n        <br>Kurfürstendamm 100\n        <br>10709 Berlin (District Wilmersdorf)\n        "
email = "info@ways-choir.eu"
name = "WAYS - WithAllYourSenses"
phone = "+49 178-2440085 (Marion)"
[params.contact.rehersal]
end = "21:45"
start = "18:45"
weekday = "Monday"
[params.imagesConfig]
cloudinaryURL = "https://res.cloudinary.com/ways-choir/image/upload"
lightboxImageDownloadSize = "w_2000"
listImageDefaultFile = "/images/ways-plakat-default.png"
listImageDownloadSize = "w_240"
logoImageDownloadSize = "w_1000"
thumbDownloadSize = "w_300,h_200,c_fill"
