baseurl = "https://ways-choir-dev.gitlab.io"
# baseurl = "http://www.ways-choir.eu/"
title = "WAYS - WithAllYourSenses"
theme = "twenty"
languageCode = "de-de"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "de"


[languages]
[languages.de]
weight = 1
languageName = "Deutsch"

[languages.en]
weight = 2
languageName = "English"


[[languages.de.menu.main]]
    url = "/contact"
    name = "Kontakt"
    weight = 1000
    identifier = "menu_contact"

[[languages.de.menu.main]]
    name   = "Über uns"
    weight = 300
    identifier = "menu_about"

[[languages.de.menu.main]]
    url    = "/about/the_choir/"
    name   = "Der Chor"
    weight = 100
    parent = "menu_about"
    identifier = "menu_about_the_choir"

[[languages.de.menu.main]]
    url    = "/events/"
    name   = "Konzerte"
    weight = 50
    parent = "menu_about"
    identifier = "menu_about_concerts"

[[languages.en.menu.main]]
    url = "/contact"
    name = "Contact"
    weight = 1000
    identifier = "menu_contact"

[[languages.en.menu.main]]
    name   = "About us"
    weight = 300
    identifier = "menu_about"

[[languages.en.menu.main]]
    url    = "/about/the_choir/"
    name   = "the choir"
    weight = 100
    parent = "menu_about"
    identifier = "menu_about_the_choir"

[[languages.en.menu.main]]
    url    = "/events/"
    name   = "Concerts"
    weight = 50
    parent = "menu_about"
    identifier = "menu_about_concerts"


[params]
    logo = "/v1577487364/logo_bg_white.png"
    email = "info@ways-choir.eu"
    # Format dates with Go's time formatting
    date_format = "2. January, 2006"
    time_format = "15:04"

    latitude = "52.4984045"
    longitude = "13.297099600000024"

[params.contact]
    name = "WAYS - WithAllYourSenses"
    address = """
        <br>Pro Seniore Residenz Kurfürstendamm
        <br>Kurfürstendamm 100
        <br>10709 Berlin (Restrict Wilmersdorf)
        """
    phone = "+49 178-2440085 (Marion)"
    email = "info@ways-choir.eu"


[params.contact.rehersal]
    weekday = "Monday"
    start = "18:45"
    end = "21:45"

[[params.languages.de]]
    address = """<p><strong>WAYS - WithAllYourSenses</strong>
        <br><strong>Proben:</strong> immer Montags von 18:45 - 21:45 Uhr
        <br>in der Pro Seniore Residenz Kurfürstendamm
        <br>Kurfürstendamm 100
        <br>10709 Berlin (Bezirk Wilmersdorf)
      </p>
      <p>
        Kontakt: +49 178-2440085 (Marion)
        <br>oder info@ways-choir.eu
      </p>
      """

[params.imagesConfig]
    cloudinaryURL = "https://res.cloudinary.com/ways-choir/image/upload"
    lightboxImageDownloadSize = "w_2000"
    logoImageDownloadSize = "w_1000"
    listImageDefaultFile = "/images/ways-plakat-default.png"
    listImageDownloadSize = "w_240"


