---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: Konfiguration der Seite
- type: directory
  path: content
  label: Startseite (Deutsch)
  create: all
  match: _index.de.md
  templates:
  - startseite
- type: directory
  path: content
  label: Startpage (English)
  create: all
  match: _index.en.md
  templates:
  - startseite
- type: directory
  path: content/events
  label: Events (Konzert, Deutsch)
  create: documents
  match: "**/*.de.md"
  exclude: _index.de.md,archive.de.md
  new_doc_ext: de.md
  templates:
  - concert
- type: directory
  path: content/events
  label: Events (English)
  create: documents
  match: "**/*.en.md"
  exclude: _index.en.md,archive.en.md
  new_doc_ext: en.md
  templates:
  - concert
- type: directory
  path: content/photos
  label: Photos (Deutsch)
  create: documents
  match: "**/*.de.md"
  exclude: _index.de.md
  new_doc_ext: de.md
  templates:
  - photoselection
- type: directory
  path: content/photos
  label: Photos (English)
  create: documents
  match: "**/*.en.md"
  exclude: _index.en.md
  new_doc_ext: en.md
  templates:
  - photoselection
- type: directory
  path: content/videos
  label: Videos (Deutsch)
  create: documents
  match: "**/*.de.md"
  new_doc_ext: de.md
  templates:
  - video
- type: directory
  path: content/videos
  label: Videos (English)
  create: documents
  match: "**/*.en.md"
  exclude: _index.en.md
  new_doc_ext: en.md
  templates:
  - video
- type: document
  path: data/repertoire.json
  label: Repertoire Data
- type: directory
  path: content
  label: Uncategorised Pages ( nicht kategorisierbare Seiten, Deutsch)
  create: documents
  match: "*.de.md"
  exclude: _index.de.md
  new_doc_ext: de.md
  templates:
  - simplepage
- type: directory
  path: content
  label: Uncategorised Pages (English)
  create: documents
  match: "*.en.md"
  exclude: _index.en.md
  new_doc_ext: en.md
  templates:
  - simplepage
upload_dir: ''
public_path: https://res.cloudinary.com/ways-choir/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.62.2
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.62.2
