---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Startseite (Deutsch)
  create: all
  match: _index.de.md
  templates:
  - startseite
- type: directory
  path: content
  label: Startpage (English)
  create: all
  match: _index.en.md
  templates:
  - startseite
- type: directory
  path: content/events
  label: Events (Konzert, Deutsch)
  create: all
  match: "**/*.de.md"
  new_doc_ext: de.md
- type: directory
  path: content/events
  label: Events (English)
  create: all
  match: "**/*.en.md"
  new_doc_ext: de.md
- type: directory
  path: content
  label: Uncategorised Pages ( nicht kathogorisierbare Seiten, Deutsch)
  create: all
  match: "**/*.de.md"
  exclude: _index.de.md
  new_doc_ext: de.md
- type: directory
  path: content
  label: Uncategorised Pages (English)
  create: all
  match: "**/*.en.md"
  exclude: _index.en.md
  new_doc_ext: en.md
upload_dir: ''
public_path: https://res.cloudinary.com/ways-choir/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: false
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.54.0
